language: ruby
script: bundle exec rspec
matrix:
  allow_failures:
  - rvm: "2.1.0"
  - rvm: "head"
  include:
  - rvm: "2.1.0"
  - rvm: "head"
  - rvm: "2.2.0"
  - rvm: "2.2.0"
    env: FPM_FRY_DOCKER=yes
    sudo: required
    services:
      - docker
  - rvm: "2.3.1"
  - rvm: "2.3.1"
    env: FPM_FRY_DOCKER=yes
    sudo: required
    services:
      - docker
  - rvm: "2.4.0"
  - rvm: "2.4.0"
    env: FPM_FRY_DOCKER=yes
    sudo: required
    services:
      - docker
